apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freshrss
  namespace: {{index . "namespace"}}
spec:
  values:
    image:
      repository: freshrss/freshrss
      pullPolicy: IfNotPresent
      tag: "1.20.2-arm"