apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freshrss
  namespace: {{ index . "namespace" }}
spec:
  serviceAccountName: {{ index . "serviceAccountName" }}
  releaseName: freshrss
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
  values:
    image:
      repository: freshrss/freshrss
      pullPolicy: IfNotPresent
      tag: 1.20.2
    strategy:
      type: Recreate
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        {{- if and (index . "isNginxInstalled") (index . "isDomainInstalled") }}
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: freshrss.{{ index . "domain"}}
            paths:
              - path: /
                pathType: Prefix
        {{- else }}
        enable: false
        {{- end }}
        {{- if and (index . "isNginxInstalled") (index . "isDomainInstalled") (index . "isCertManagerInstalled") }}
        tls:
          - secretName: freshrss-cert
            hosts:
              - freshrss.{{ index . "domain"}}
        {{- end }}
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
        mountPath: /var/www/FreshRSS/data
    env:
      TZ: Europe/Paris
      CRON_MIN: '2,32'
      